on:
  schedule:
    - cron: '1 6,11,16,21 * * *'
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: Get daily satellite data

jobs:
  render:
    name: Get daily satellite data
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies and packages
        run: Rscript -e 'install.packages(c("stringr","readr","dplyr"))'
      - name: Collect today's fire, smoke files
        run: Rscript scripts/get_satellite_data.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'New satellite data fetched!' || echo "No changes"
          git push origin || echo "No changes to commit"
          
